# Generated by Django 2.2.6 on 2019-10-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published', models.DateField()),
                ('created_by', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
