# Generated by Django 2.2.6 on 2019-10-07 02:56

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=markdownx.models.MarkdownxField(help_text='You can write in Markdown', verbose_name='body'),
        ),
    ]
