# Generated by Django 2.2.6 on 2019-10-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_id', models.CharField(max_length=255)),
                ('disable', models.BooleanField(default=False)),
                ('file_object_path', models.CharField(max_length=255)),
            ],
        ),
    ]
