# Generated by Django 3.0.5 on 2020-05-13 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('mtg_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('on_start', models.BooleanField()),
                ('on_end', models.BooleanField()),
                ('presenters', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPresenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenter_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFilesRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_uri', models.CharField(max_length=255)),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.MeetingPresenter')),
            ],
        ),
    ]
